name: Called workflow

on:
  workflow_dispatch:
    inputs:
      myInput:
        description: 'My input'
        required: true
        default: 'default value'

jobs:
  calledwfl:
    runs-on: ubuntu-latest
    steps:
      - name: Called workflow
        run: echo ${{ github.event.inputs.myInput }}
