name: Called workflow

on:
  push:
    branches:
      - master

jobs:
  calledwfl:
    runs-on: ubuntu-latest
    steps:
      - name: Called workflow
        run: echo ${{ github.event.inputs.myInput }}
